### PR TITLE
Add links #17

### PR DESCRIPTION
**Pull request by rudrajit1729**
References to readme file added to code

### CODE REVIEW

**Comment by rudrajit1729** [comment]
Added links to documentation in comments #17

**Comment by ujjwalll** [comment]
Hello @rudrajit1729, Thank you for your interest in DevoLearn, You can go through contribution.md once, to know about devolearn and its contribution guidelines.

This PR looks good to me.

**Comment by rudrajit1729** [comment]
Hi @ujjwalll , I have taken a look at contributing.md and it seems PR has the necessary things. Can you merge it now? If there is something for me to fix here please do let me know. Thank you.

**Comment by rudrajit1729** [comment]
Changed 3 files updated the commit message. One commit was having an issue with Travis ci fixed that too. If this passes and the reviews are done feel free to merge this. Thanks.

**Pull request merged**
